In [23]:
import numpy as np
import random
import math
import matplotlib.pyplot as plt

In [24]:
alp = 0.5

In [25]:
arr = [[0,0],[0,1],[1,0],[1,1]]
inp = np.array(arr)
inp

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [26]:
arr1 = [[0,0],[0,0],[0,1],[1,1]] 
out = np.array(arr1)
out

array([[0, 0],
       [0, 0],
       [0, 1],
       [1, 1]])

In [27]:
perceptrons_weights = []
for i in range(6): 
    perceptrons_weights.append(random.randrange(45,55))
lw1 = perceptrons_weights[:2]
lw2 = perceptrons_weights[2:4]
lw3 = perceptrons_weights[4:6]
wt = np.array([lw1,lw2,lw3]) 
wt

array([[53, 48],
       [49, 54],
       [50, 49]])

In [28]:
def multiply(perceptrons_weights,sigarray):  
    mul = perceptrons_weights*sigarray
    return mul

In [29]:
def sigmoid(x):
    z = 1/(1 + np.exp(-x))
    return z
vector = np.vectorize(sigmoid) 

for i in range(0,len(inp)):
    layer1 = vector(multiply(wt[0],inp[i])) #Values for layer1 (Input layer)
    layer2 = vector(multiply(wt[1],layer1)) #Values for layer2 (Hidden layer)
    layer3 = vector(multiply(wt[2],layer2)) #Values for layer3 (Output layer)
    
    #Backward Propagation
    
    er3 = (out[i] - layer3)*(np.ones(2) - layer3)*layer3*layer2 
    wt[2] = wt[2] + (alp * er3)
    er2 = (out[i] - layer3)*(np.ones(2) - layer3)* layer3 * wt[2] * (np.ones(2) - layer2) * layer2 * layer1 
    wt[1] = wt[1] + (alp * er2)
    er1 = (out[i] - layer3)*(np.ones(2) - layer3)*layer3*wt[2]*(np.ones(2) - layer2)*layer2*wt[1]*(np.ones(2) - layer1)*layer1*inp[i] 
    wt[0] = wt[0] + (alp * er1) 
print(wt)


[[53 48]
 [49 54]
 [50 49]]


In [30]:
sample = np.array([1,1]) 
sample

array([1, 1])

In [31]:
layer1 = vector(multiply(wt[0],sample))
layer2 = vector(multiply(wt[1],sample)) 
layer3 = vector(multiply(wt[2],sample)) 

In [32]:
layer3

array([1., 1.])

In [33]:
import tensorflow as tf
from tensorflow import keras

In [34]:
# Input arrays
a = np.array([0, 0, 1, 1])
b = np.array([0, 1, 0, 1])
# Output array
out = np.array([0, 0, 0, 1])
# Final input array is obtained after combining the input elements into a new array.
total_input = []

for i, j in zip(a, b):
    input1 = []
    input1.append(i)
    input1.append(j)
    total_input.append(input1)
    
total_input = np.array(total_input) #Final input array
total_input

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [43]:
x_train = []
y_train = []

for i, j in zip(total_input, out):
    x_train.append(i)
    y_train.append(j)
    
x_train = np.array(x_train)
y_train = np.array(y_train)

In [44]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.models import Sequential

model = keras.Sequential(name="my_sequential")
model.add(Input(shape = x_train[0].shape))
model.add(Dense(10, activation = "relu"))
model.add(Dense(10, activation = "relu"))
model.add(Dense(1, activation = "sigmoid"))
model.summary()

Model: "my_sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 10)                30        
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 1)                 11        
                                                                 
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.compile(optimizer = "adam", loss = "binary_crossentropy", metrics = "binary_accuracy")

In [46]:
model.fit(x_train, y_train, epochs = 500)

Epoch 1/500
1/1 [==============================] - 1s 953ms/step - loss: 0.7231 - binary_accuracy: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7214 - binary_accuracy: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7197 - binary_accuracy: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7181 - binary_accuracy: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7164 - binary_accuracy: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7149 - binary_accuracy: 0.5000
Epoch 7/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7133 - binary_accuracy: 0.5000
Epoch 8/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7118 - binary_accuracy: 0.5000
Epoch 9/500
1/1 [==============================] - 0s 4ms/step - loss: 0.7102 - binary_accuracy: 0.5000
Epoch 10/500
1/1 [==============================] - 0s 5ms/ste

1/1 [==============================] - 0s 5ms/step - loss: 0.6416 - binary_accuracy: 1.0000
Epoch 80/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6408 - binary_accuracy: 1.0000
Epoch 81/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6400 - binary_accuracy: 1.0000
Epoch 82/500
1/1 [==============================] - 0s 6ms/step - loss: 0.6392 - binary_accuracy: 1.0000
Epoch 83/500
1/1 [==============================] - 0s 5ms/step - loss: 0.6385 - binary_accuracy: 1.0000
Epoch 84/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6377 - binary_accuracy: 1.0000
Epoch 85/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6370 - binary_accuracy: 1.0000
Epoch 86/500
1/1 [==============================] - 0s 4ms/step - loss: 0.6362 - binary_accuracy: 1.0000
Epoch 87/500
1/1 [==============================] - 0s 7ms/step - loss: 0.6354 - binary_accuracy: 1.0000
Epoch 88/500
1/1 [==============================] - 0s 5ms/step - lo

1/1 [==============================] - 0s 6ms/step - loss: 0.5770 - binary_accuracy: 1.0000
Epoch 157/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5761 - binary_accuracy: 1.0000
Epoch 158/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5751 - binary_accuracy: 1.0000
Epoch 159/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5742 - binary_accuracy: 1.0000
Epoch 160/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5731 - binary_accuracy: 1.0000
Epoch 161/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5722 - binary_accuracy: 1.0000
Epoch 162/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5712 - binary_accuracy: 1.0000
Epoch 163/500
1/1 [==============================] - 0s 6ms/step - loss: 0.5702 - binary_accuracy: 1.0000
Epoch 164/500
1/1 [==============================] - 0s 5ms/step - loss: 0.5693 - binary_accuracy: 1.0000
Epoch 165/500
1/1 [==============================] - 0s 5ms/

1/1 [==============================] - 0s 6ms/step - loss: 0.4679 - binary_accuracy: 1.0000
Epoch 234/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4655 - binary_accuracy: 1.0000
Epoch 235/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4632 - binary_accuracy: 1.0000
Epoch 236/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4607 - binary_accuracy: 1.0000
Epoch 237/500
1/1 [==============================] - 0s 7ms/step - loss: 0.4584 - binary_accuracy: 1.0000
Epoch 238/500
1/1 [==============================] - 0s 5ms/step - loss: 0.4560 - binary_accuracy: 1.0000
Epoch 239/500
1/1 [==============================] - 0s 6ms/step - loss: 0.4536 - binary_accuracy: 1.0000
Epoch 240/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4512 - binary_accuracy: 1.0000
Epoch 241/500
1/1 [==============================] - 0s 4ms/step - loss: 0.4489 - binary_accuracy: 1.0000
Epoch 242/500
1/1 [==============================] - 0s 4ms/

1/1 [==============================] - 0s 9ms/step - loss: 0.3136 - binary_accuracy: 1.0000
Epoch 311/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3118 - binary_accuracy: 1.0000
Epoch 312/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3099 - binary_accuracy: 1.0000
Epoch 313/500
1/1 [==============================] - 0s 6ms/step - loss: 0.3080 - binary_accuracy: 1.0000
Epoch 314/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3062 - binary_accuracy: 1.0000
Epoch 315/500
1/1 [==============================] - 0s 7ms/step - loss: 0.3043 - binary_accuracy: 1.0000
Epoch 316/500
1/1 [==============================] - 0s 9ms/step - loss: 0.3025 - binary_accuracy: 1.0000
Epoch 317/500
1/1 [==============================] - 0s 10ms/step - loss: 0.3008 - binary_accuracy: 1.0000
Epoch 318/500
1/1 [==============================] - 0s 6ms/step - loss: 0.2991 - binary_accuracy: 1.0000
Epoch 319/500
1/1 [==============================] - 0s 7ms

1/1 [==============================] - 0s 6ms/step - loss: 0.1915 - binary_accuracy: 1.0000
Epoch 388/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1902 - binary_accuracy: 1.0000
Epoch 389/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1889 - binary_accuracy: 1.0000
Epoch 390/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1877 - binary_accuracy: 1.0000
Epoch 391/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1864 - binary_accuracy: 1.0000
Epoch 392/500
1/1 [==============================] - 0s 4ms/step - loss: 0.1851 - binary_accuracy: 1.0000
Epoch 393/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1838 - binary_accuracy: 1.0000
Epoch 394/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1826 - binary_accuracy: 1.0000
Epoch 395/500
1/1 [==============================] - 0s 8ms/step - loss: 0.1814 - binary_accuracy: 1.0000
Epoch 396/500
1/1 [==============================] - 0s 5ms/

1/1 [==============================] - 0s 6ms/step - loss: 0.1129 - binary_accuracy: 1.0000
Epoch 465/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1122 - binary_accuracy: 1.0000
Epoch 466/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1114 - binary_accuracy: 1.0000
Epoch 467/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1107 - binary_accuracy: 1.0000
Epoch 468/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1099 - binary_accuracy: 1.0000
Epoch 469/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1092 - binary_accuracy: 1.0000
Epoch 470/500
1/1 [==============================] - 0s 7ms/step - loss: 0.1085 - binary_accuracy: 1.0000
Epoch 471/500
1/1 [==============================] - 0s 6ms/step - loss: 0.1077 - binary_accuracy: 1.0000
Epoch 472/500
1/1 [==============================] - 0s 5ms/step - loss: 0.1070 - binary_accuracy: 1.0000
Epoch 473/500
1/1 [==============================] - 0s 7ms/

In [47]:
model.predict(x_train)

1/1 [==============================] - 0s 265ms/step


array([[0.0927017 ],
       [0.08780257],
       [0.09008154],
       [0.9319437 ]], dtype=float32)